### ISSUE TITLE
Cropping in large messages

### ISSUE THREAD

**Issue by Samuc** [coddingtonbear/django-mailbox#107] opened 2016-08-01 15:22 UTC
When I send to my mailbox large messages (for instance with more than 30000 characters), then the messages are cropped in the message I get in the mailbox. 

I have been testing with the code of the package, and in "models.py" file, in the function "get_new_mail", after this action: 
msg = self.process_incoming_message(message)
The msg object will have already the message cropped.
I checked the content of the message (returned by the connector) and it has the full text I sent.

Creating an eml file (with message.get_email_object().as_string() )  ) of the cropped message result I have in my mailbox, I see that all of the eml files of the cropped messages has a maximum size of 20kb (between 19 and 20, always less than 20).

Do you have any idea of this problem?

**Comment by ad-m** [comment] 2016-08-01 16:15
Do you can provide test code? What backend do you use? MySQL?

Wysłano z urządzenia mobilnego.

1 sie 2016 5:22 PM "Samuel Carmona" <notifications@github.com> napisał(a):

**Comment by Samuc** [comment] 2016-08-01 16:36
I tested it directly in the models.py, to verify where the message was being cropped. 

 def get_new_mail(self, condition=None):
        """Connect to this transport and fetch new messages."""
        new_mail = []
        connection = self.get_connection()
        if not connection:
            return new_mail
        for message in connection.get_message(condition):
            print "Message before processing:"
            print message.as_string()  #This has the full content I sent (I sent just plain text with normal characters)

            msg = self.process_incoming_message(message)

            print "Message after processing:"
            print msg.get_email_object().as_string()   #Cropped message

            new_mail.append(msg)
        return new_mail

So, in the second print, the message has already been cropped.

**Comment by ad-m** [comment] 2016-08-01 19:01
I have issue with preparing messages which fail. Eg.
```
    def test_long_message(self):
        mailbox = Mailbox.objects.create(from_email='from@example.com')

        content = "A"*(30*1000)

        message = MIMEText(content)
        message['Subject'] = message['From'] = "data@example.com"

        msg = mailbox._process_message(message)

        self.assertEqual(len(content), len(msg.text))
```
It doesn’t have provide any issues. Do you can prepare *.eml file?

**Comment by ad-m** [comment] 2016-08-01 19:06
I mark that you comppare messages object than text content. I don't have issues too. 
```
    def test_long_message(self):
        mailbox = Mailbox.objects.create(from_email='from@example.com')

        content = "A"*(30*1000)

        message = MIMEText(content)
        message['Subject'] = message['From'] = "data@example.com"

        msg = mailbox._process_message(message)
        msg.refresh_from_db()
        self.assertEqual(len(message.as_string()),
                         len(msg.get_email_object().as_string()))
```

I am unable to help without prepared a *.eml file which fail. Redact sensitive data, please.

**Comment by Samuc** [comment] 2016-08-01 19:10
Okey, for instance I sent to my inbox a message with the content of the next file as the body message: (in gmail)
[content_sent_message.txt](https://github.com/coddingtonbear/django-mailbox/files/394577/content_sent_message.txt)
(The text is just a plain text pasted 10 times, in order to achieve a large message)

And then, this is the eml file I have created from msg object Django Mailbox creates: (I put .txt extension instead of .eml for attaching it here)
[eml file processed in mailbox.txt](https://github.com/coddingtonbear/django-mailbox/files/394578/eml.file.processed.in.mailbox.txt)

As you can see, the text is cropped in the fifth paste.

**Comment by ad-m** [comment] 2016-08-01 19:16
What database do you use?  Do you can provide SQL CREATE TABLE schema on your DBMS?

It pass:
```python
    @staticmethod
    def _get_email_object(filename):  # See coddingtonbear/django-mailbox#89
        path = join(dirname(__file__), 'messages', filename)
        fp = open(path, 'rb')
        return message_from_file(fp)
    def test_long_message(self):
        mailbox = Mailbox.objects.create(from_email='from@example.com')

        message = self._get_email_object("long_message.eml")

        msg = mailbox._process_message(message)

        self.assertEqual(len(message.as_string()),
                         len(msg.get_email_object().as_string()))
```

**Comment by Samuc** [comment] 2016-08-01 19:31
Hmm, we use it in a big system, retrieving messages from users. We use Mysql.

But has that something to do with the issue?

In the first code I put:
```
print "Message before processing:"
            print message.as_string()  #This has the full content I sent (I sent just plain text with normal characters)

            msg = self.process_incoming_message(message)

            print "Message after processing:"
            print msg.get_email_object().as_string()   #Cropped message
```
And both strings I show on screen, they are not equal, one is cropped before the half of all the text. (you can see it in the eml file I created, in the original message I sent, I paste the same text 10 times and after each paste I put a mark number "1111111", "22222", etc, so it is cropped before the fifth pasted text)
The crop ocurs in "self.process_incoming_message(message)", that then calls to "_process_message(message)"

Is there something that do the crop when the message is too large?

**Comment by coddingtonbear** [comment] 2016-08-01 20:01
I'm afraid not, Samuc; there is no built-in cropping behavior.  If you have this message in Gmail, though, you could give us something to work with by clicking the little downward-facing arrow in Gmail (![](https://www.dropbox.com/s/8sqwmgoq1yqq8pp/Screenshot%202016-08-01%2012.59.59.png?dl=1)), clicking "Show Original", and then sending us a gist of that.

**Comment by ad-m** [comment] 2016-08-01 20:03
I don't know anything what can make crop messages in django-mailbox. I unable to reporduce your issues on my host.

I supposed it might happened in DBMS (this is why I ask about that), but it don't.

Do you use python 2.7 or python 3? Django-mailbox use python standard library internally, so there might be some differences.

Do you can test that in your environment?  It pass or not?
```python
from os.path import dirname

from django.test import TestCase
from django_mailbox.transports.base import EmailTransport
from django_mailbox.models import Mailbox


class CropTestCase(TestCase):
    def test_long_message(self):

        mailbox = Mailbox.objects.create(from_email='from@example.com')

        # Construct messsages like your one
        path = dirname(__file__) + '/messages/long_message.eml'
        message = EmailTransport().get_email_from_bytes(open(path, 'rb').read())  # ImapTransport use that internally

        # Save size as int, so unchangable later by reference
        size = len(message.as_string())

        # Process
        msg = mailbox.process_incoming_message(message)

        # Compare
        self.assertEqual(size,
                         len(msg.get_email_object().as_string()))
```

**Comment by Samuc** [comment] 2016-08-01 20:29
This is the"Show Original" of the message I contains entirely the message I sent (until the "10101010" string I added at the fifth text paste)
[show_original.txt](https://github.com/coddingtonbear/django-mailbox/files/394710/show_original.txt)

To compare with the eml text I obtain from django mailbox:
[eml file processed in mailbox.txt](https://github.com/coddingtonbear/django-mailbox/files/394711/eml.file.processed.in.mailbox.txt)

Ad-m, Im not at work office right now to try that, but I checked it manually, printing, and they have not the same lenght, one is cutted before the half like I said. (I will try again tomorrow, but I checked it manually).

[Thanks for your replies!]

**Comment by Samuc** [comment] 2016-08-02 10:58
ad-m, I tried that code, and it doesnt pass it. 

As I checked manually at the beginning, the msg file has cropped message.

We are using Python 2.7.6.

**Comment by ad-m** [comment] 2016-08-03 15:48
The variable ```message``` should contains message from your ```.eml```. It pass for me on python 2.7.10, so it's very weird what happened.

Do you use any signals to procdss incoming emails https://django-mailbox.readthedocs.io/en/latest/topics/signal.html ?

**Comment by ad-m** [comment] 2016-08-03 17:02
I am unable to reproduce your issue in any environment. 

I made fork with added test ( https://github.com/ad-m/django-mailbox/commit/3e003c4acb5f ) and it pass in Travis ( https://travis-ci.org/ad-m/django-mailbox/builds/149525720 ) except Python 1.6. Python 1.6 EOT at 2013-10-29, so it doesn't matter for me ( https://docs.python.org/devguide/#status-of-python-branches ). I suggest drop test for python 2.6 (#108).

**Comment by Samuc** [comment] 2016-08-03 18:00
Okey, its fixed, it was a long story, and the django mailbox was working fine at the end.

It was that we use it in a big app, built a long time ago, and at some point, they override the content from a processing function outside of it, from the app code (and it was added there a characters limitation). So I didnt know about it till I have researched deeply.

So, sorry for the spent time, and thank you both for the replies!

**Comment by ad-m** [comment] 2016-08-03 18:08
You can public wrote where and for what do you use the library and add pull requests to docs about that? It might be good to promote django-mailbox as reliably, useful, battle-tested library.  It might improve raising community, so it will improve maintain library and the bugs (even exists some) will be identified and fixed faster.

**Comment by ad-m** [comment] 2016-08-15 20:30
@coddingtonbear , do you can close this issue?

**Closed** 2016-08-15 20:54 UTC
